### ISSUE TITLE
ECS AMI IDs out-of-date?

### ISSUE THREAD

**Issue by pedros007** [mvanholsteijn/ecs-docker-run#1]
Where did you get your ECS AMI IDs in `ecs.json`?

```
    "EcsAmiIds": {
      "ap-northeast-1": {
        "id": "ami-8aa61c8a"
      },
      "ap-southeast-2": {
        "id": "ami-5ddc9f67"
      },
      "eu-west-1": {
        "id": "ami-2aaef35d"
      },
      "us-east-1": {
        "id": "ami-b540eade"
      },
      "us-west-1": {
        "id": "ami-5721df13"
      },
      "us-west-2": {
        "id": "ami-cb584dfb"
      }
    }
```

The [ones listed in the Docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html) match what I see in my AWS Console, which I think should be:

```
        "EcsAmiIds": {
            "ap-northeast-1": {
                "id": "ami-ce2ba4ce"
            },
            "ap-southeast-2": {
                "id": "ami-3f531f05"
            },
            "eu-west-1": {
                "id": "ami-bd5572ca"
            },
            "us-east-1": {
                "id": "ami-4fe4852a"
            },
            "us-west-1": {
                "id": "ami-2708f363"
            },
            "us-west-2": {
                "id": "ami-8bd4c7bb"
            }
        }
```

**Comment by mvanholsteijn** [comment]
Hi Pete,

The cloudformation file was copied from the [firstRun](https://console.aws.amazon.com/ecs/home?region=us-east-1#/firstRun) wizard and refers to the slightly older version of the ECS machine image  of august 14th. (amzn-ami-2015.03.f-amazon-ecs-optimized) 

The version you refer to (amzn-ami-2015.03.g-amazon-ecs-optimized) is, from september 3rd.

Cheers,

Mark
